name: 'build'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
      - name: Compress node_modules
        run: tar -czvf node_modules.tar.gz ./node_modules
      - uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.tar.gz
          retention-days: 1